# Generated by Django 5.2.7 on 2025-12-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_alter_blogpost_image_alter_compound_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='max_installment_years',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum installment years available', null=True),
        ),
        migrations.AddField(
            model_name='compound',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Starting price for the project', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Expected delivery date', null=True),
        ),
    ]
