# Generated by Django 5.2.7 on 2025-12-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_compound_max_installment_years_compound_min_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='min_area',
            field=models.PositiveIntegerField(blank=True, help_text='Starting area in square meters', null=True),
        ),
    ]
