# Generated by Django 5.2.7 on 2025-12-18 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_compound_min_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compound',
            name='is_new_launch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compound',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='compounds/map_images/'),
        ),
        migrations.AddField(
            model_name='compound',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL (YouTube)'),
        ),
        migrations.CreateModel(
            name='CompoundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='compounds/gallery/')),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='realestate.compound')),
            ],
        ),
    ]
